spring:
  application:
    name: oauth2-resource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz949qd557877lei3o.mysql.rds.aliyuncs.com:3306/oauth2_resource?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ibest_admin
    password: ibest_admin@2017!hh
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


server:
  port: 8889
  servlet:
    context-path: /contents

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:8999/oauth/token
      user-authorization-uri: http://localhost:8999/oauth/authorize
    resource:
      token-info-uri: http://localhost:8999/oauth/check_token


mybatis:
  type-aliases-package: com.htisec.oauth2.resource.domain
  mapper-locations: classpath:mapper/*.xml
